let data = [
  {
    id: 23,
    prize_image: "uploads\\666元免单券.png",
    prize_name: "666元免单券",
    win_probability: "0.00",
    redemption_image: "uploads/谢谢参与.png",
    activity_id: 5,
    stock: 0,
  },
  {
    id: 24,
    prize_image: "uploads\\100-25.png",
    prize_name: "100-25优惠券",
    win_probability: "10.00",
    redemption_image: "uploads/1兑奖券-满100减25优惠券.png",
    activity_id: 5,
    stock: 97,
  },
  {
    id: 25,
    prize_image: "uploads\\3元无门槛.png",
    prize_name: "3元无门槛券",
    win_probability: "1.00",
    redemption_image: "uploads/1兑奖券-3元无门槛.png",
    activity_id: 5,
    stock: 10,
  },
  {
    id: 26,
    prize_image: "uploads/50-10优惠券.png",
    prize_name: "50-10优惠券",
    win_probability: "5.00",
    redemption_image: "uploads/1兑奖券-50-10优惠券.png",
    activity_id: 5,
    stock: 98,
  },
  {
    id: 27,
    prize_image: "uploads\\10元无门槛.png",
    prize_name: "10元无门槛券",
    win_probability: "44.00",
    redemption_image: "uploads/1兑奖券-10元无门槛券.png",
    activity_id: 5,
    stock: 986,
  },
  {
    id: 28,
    prize_image: "uploads\\5元无门槛.png",
    prize_name: "5元无门槛券",
    win_probability: "40.00",
    redemption_image: "uploads/1兑奖券-5元无门槛券.png",
    activity_id: 5,
    stock: 30,
  },
];
